[package]
name = "hq-protocol-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
hq-protocol = { version = "0.1.0", path = ".." }

[[bin]]
name = "signed_event"
path = "fuzz_targets/signed_event.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
