[package]
name = "hq-protocol"
description = "Canonical and remote-control protocols for HQ"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
hq-domain.workspace = true

[lints]
workspace = true
